#ifndef __wxHelloProjectPanelMain__
#define __wxHelloProjectPanelMain__

/**
@file
Subclass of PanelMain, which is generated by wxFormBuilder.
*/

#include "wxHelloGenerated.h"

//// end generated include

/** Implementing PanelMain */
class wxHelloProjectPanelMain : public PanelMain
{
	protected:
		// Handlers for PanelMain events.
		void on_hello_button_clicked( wxCommandEvent& event );
	public:
		/** Constructor */
		wxHelloProjectPanelMain( wxWindow* parent );
	//// end generated class members
	
};

#endif // __wxHelloProjectPanelMain__
