#ifndef __wxHelloProjectFrameMain__
#define __wxHelloProjectFrameMain__

/**
@file
Subclass of FrameMain, which is generated by wxFormBuilder.
*/

#include "wxHelloGenerated.h"

//// end generated include

/** Implementing FrameMain */
class wxHelloProjectFrameMain : public FrameMain
{
	public:
		/** Constructor */
		wxHelloProjectFrameMain( wxWindow* parent );
	//// end generated class members
	
};

#endif // __wxHelloProjectFrameMain__
